<a href="https://colab.research.google.com/github/Himanshu3557/Data-science-dashboard-project/blob/main/project3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install plotly -q

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

In [2]:
flow_data = pd.DataFrame({
    "Source": [
        "VC Funds",
        "VC Funds",
        "Government",
        "Government",
        "Corporations",
        "Corporations"
    ],

    "Target": [
        "Generative AI",
        "Healthcare AI",
        "Healthcare AI",
        "Agriculture AI",
        "Generative AI",
        "FinTech AI"
    ],

    "Value": [
        500,
        300,
        250,
        200,
        400,
        350
    ]
})

flow_data

         Source          Target  Value
0      VC Funds   Generative AI    500
1      VC Funds   Healthcare AI    300
2    Government   Healthcare AI    250
3    Government  Agriculture AI    200
4  Corporations   Generative AI    400
5  Corporations      FinTech AI    350

In [3]:
sunburst_data = pd.DataFrame({
    "Sector": [
        "Generative AI",
        "Generative AI",
        "Generative AI",
        "Healthcare AI",
        "Healthcare AI",
        "Agriculture AI",
        "FinTech AI"
    ],

    "Application": [
        "Chatbots",
        "Image Generation",
        "Video Generation",
        "Medical Diagnosis",
        "Drug Discovery",
        "Smart Farming",
        "Fraud Detection"
    ],

    "Investment": [
        450,
        250,
        200,
        350,
        200,
        200,
        350
    ]
})

sunburst_data

           Sector        Application  Investment
0   Generative AI           Chatbots         450
1   Generative AI   Image Generation         250
2   Generative AI   Video Generation         200
3   Healthcare AI  Medical Diagnosis         350
4   Healthcare AI     Drug Discovery         200
5  Agriculture AI      Smart Farming         200
6      FinTech AI    Fraud Detection         350

In [4]:
labels = list(
    pd.concat([
        flow_data["Source"],
        flow_data["Target"]
    ]).unique()
)

label_dict = {label: idx for idx, label in enumerate(labels)}

source = flow_data["Source"].map(label_dict)
target = flow_data["Target"].map(label_dict)
value = flow_data["Value"]

fig_sankey = go.Figure(data=[
    go.Sankey(
        node=dict(
            pad=20,
            thickness=20,
            line=dict(color="black", width=0.5),
            label=labels,
            color=[
                "#1f77b4","#1f77b4","#1f77b4",
                "#ff7f0e","#2ca02c","#d62728","#9467bd"
            ]
        ),

        link=dict(
            source=source,
            target=target,
            value=value,

            hovertemplate=
            "<b>%{source.label}</b> → <b>%{target.label}</b><br>"
            "Investment: $%{value} Million<extra></extra>"
        )
    )
])

fig_sankey.update_layout(
    title={
        "text":"AI Investment Flow Dashboard",
        "x":0.5
    },
    font_size=12,
    width=1100,
    height=650
)

fig_sankey.show()

In [5]:
fig_sunburst = px.sunburst(
    sunburst_data,
    path=["Sector", "Application"],
    values="Investment",
    color="Sector",
    title="AI Sector Investment Breakdown"
)

fig_sunburst.update_traces(
    hovertemplate=
    "<b>%{label}</b><br>"
    "Investment: $%{value} Million<br>"
    "Contribution: %{percentRoot:.1%}"
    "<extra></extra>"
)

fig_sunburst.update_layout(
    title={
        "text":"AI Industry Hierarchy",
        "x":0.5
    },
    width=900,
    height=700
)

fig_sunburst.show()